name: bot_gosse
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.0.6

dependencies:
  nyxx: ^6.0.0-dev.1
  shaburger: ^0.2.0
  bel_adn:
    git: https://github.com/shalien/bel_adn.git
  sha_env: 
    git: https://github.com/shalien/sha_env.git


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
